import { Exercise } from '../types';

export const defaultExercises: Omit<Exercise, 'id' | 'userId' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Barbell Squat',
    muscleGroup: 'Legs',
    equipment: 'Barbell',
    instructions: 'Place barbell on upper back. Feet shoulder-width apart. Lower hips until thighs are parallel to floor. Drive through heels to stand.',
  },
  {
    name: 'Deadlift',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    instructions: 'Stand with feet hip-width apart, barbell over mid-foot. Hinge at hips, grip bar. Keep back flat, drive through heels to stand.',
  },
  {
    name: 'Bench Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    instructions: 'Lie on bench, grip bar slightly wider than shoulders. Lower to chest, press up until arms are fully extended.',
  },
  {
    name: 'Overhead Press',
    muscleGroup: 'Shoulders',
    equipment: 'Barbell',
    instructions: 'Stand with bar at upper chest. Press bar straight up until arms are locked. Lower with control.',
  },
  {
    name: 'Pull-Up',
    muscleGroup: 'Back',
    equipment: 'Pull-Up Bar',
    instructions: 'Hang from bar with palms facing away. Pull body up until chin clears bar. Lower with control.',
  },
  {
    name: 'Dumbbell Row',
    muscleGroup: 'Back',
    equipment: 'Dumbbell',
    instructions: 'Hinge at hip with dumbbell in hand. Pull weight to hip, squeezing shoulder blade. Lower with control.',
  },
  {
    name: 'Leg Press',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    instructions: 'Sit in leg press machine. Place feet on platform shoulder-width apart. Lower platform until knees are at 90 degrees. Press back up.',
  },
  {
    name: 'Romanian Deadlift',
    muscleGroup: 'Hamstrings',
    equipment: 'Barbell',
    instructions: 'Hold bar at hip level. Hinge at hips, lowering bar along legs while keeping back flat. Return to standing.',
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    instructions: 'Lie on incline bench. Press dumbbells from chest to full extension. Lower with control.',
  },
  {
    name: 'Lateral Raise',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbell',
    instructions: 'Hold dumbbells at sides. Raise arms out to sides until parallel with floor. Lower slowly.',
  },
  {
    name: 'Bicep Curl',
    muscleGroup: 'Arms',
    equipment: 'Dumbbell',
    instructions: 'Hold dumbbells with palms facing forward. Curl weights toward shoulders. Lower slowly.',
  },
  {
    name: 'Tricep Dip',
    muscleGroup: 'Arms',
    equipment: 'Bodyweight',
    instructions: 'Place hands on parallel bars or bench edge. Lower body by bending elbows. Press back up.',
  },
  {
    name: 'Leg Curl',
    muscleGroup: 'Hamstrings',
    equipment: 'Machine',
    instructions: 'Lie face down on leg curl machine. Curl heels toward glutes. Lower with control.',
  },
  {
    name: 'Leg Extension',
    muscleGroup: 'Quadriceps',
    equipment: 'Machine',
    instructions: 'Sit in leg extension machine. Extend legs until knees are straight. Lower with control.',
  },
  {
    name: 'Calf Raise',
    muscleGroup: 'Calves',
    equipment: 'Machine',
    instructions: 'Place balls of feet on platform. Lower heels below platform, then raise up onto toes.',
  },
  {
    name: 'Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    instructions: 'Sit at lat pulldown machine. Pull bar down to upper chest. Return with control.',
  },
  {
    name: 'Cable Fly',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    instructions: 'Stand between cable columns. Bring handles together in front of chest. Return with control.',
  },
  {
    name: 'Face Pull',
    muscleGroup: 'Shoulders',
    equipment: 'Cable',
    instructions: 'Pull rope attachment toward face, separating hands at end. Squeeze rear delts. Return with control.',
  },
  {
    name: 'Plank',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    instructions: 'Hold push-up position on forearms. Keep body straight from head to heels. Hold for time.',
  },
  {
    name: 'Russian Twist',
    muscleGroup: 'Core',
    equipment: 'Dumbbell',
    instructions: 'Sit with knees bent, lean back slightly. Twist torso side to side, touching weight to floor.',
  },
  {
    name: 'Hip Thrust',
    muscleGroup: 'Glutes',
    equipment: 'Barbell',
    instructions: 'Sit with upper back against bench, barbell over hips. Thrust hips up, squeezing glutes. Lower with control.',
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Legs',
    equipment: 'Dumbbell',
    instructions: 'Place rear foot on bench behind you. Lower into lunge, then drive up through front heel.',
  },
  {
    name: 'Chest Dip',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    instructions: 'Lean forward on parallel bars. Lower body until shoulders are below elbows. Press up.',
  },
  {
    name: 'Seated Row',
    muscleGroup: 'Back',
    equipment: 'Cable',
    instructions: 'Sit at cable row station. Pull handle to lower ribs, squeezing shoulder blades. Return with control.',
  },
  {
    name: 'Skull Crusher',
    muscleGroup: 'Arms',
    equipment: 'Barbell',
    instructions: 'Lie on bench, hold bar over chest. Lower bar to forehead by bending elbows. Extend arms.',
  },
  {
    name: 'Hammer Curl',
    muscleGroup: 'Arms',
    equipment: 'Dumbbell',
    instructions: 'Hold dumbbells with palms facing each other. Curl toward shoulders. Lower with control.',
  },
  {
    name: 'Front Squat',
    muscleGroup: 'Legs',
    equipment: 'Barbell',
    instructions: 'Hold bar across front shoulders. Squat down, keeping torso upright. Drive through heels to stand.',
  },
  {
    name: 'Good Morning',
    muscleGroup: 'Hamstrings',
    equipment: 'Barbell',
    instructions: 'Place bar on upper back. Hinge at hips, lowering torso until nearly parallel. Return to standing.',
  },
  {
    name: 'Push-Up',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    instructions: 'Start in plank position. Lower chest to floor, then press back up. Keep body straight.',
  },
  {
    name: 'Mountain Climber',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    instructions: 'In plank position, alternate bringing knees toward chest in running motion. Keep hips low.',
  },
  {
    name: 'Goblet Squat',
    muscleGroup: 'Legs',
    equipment: 'Dumbbell',
    instructions: 'Hold dumbbell at chest. Squat down, keeping chest up. Drive through heels to stand.',
  },
  {
    name: 'Arnold Press',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbell',
    instructions: 'Start with palms facing you at shoulder height. Press up while rotating palms forward.',
  },
  {
    name: 'Cable Crunch',
    muscleGroup: 'Core',
    equipment: 'Cable',
    instructions: 'Kneel facing cable machine, rope behind head. Crunch down, bringing elbows toward knees.',
  },
  {
    name: 'Box Jump',
    muscleGroup: 'Legs',
    equipment: 'Box',
    instructions: 'Stand in front of box. Bend knees and jump onto box, landing softly. Step down and repeat.',
  },
  {
    name: 'Farmer Carry',
    muscleGroup: 'Core',
    equipment: 'Dumbbell',
    instructions: 'Hold heavy dumbbells at sides. Walk with upright posture for distance or time.',
  },
];
